svg_icons:
  default: "moon|sun"
  type: "list"
  list_type: "compact"
add_color_scheme_toggle_to_header:
  default: false
  type: bool
  description: "Add color scheme toggle button to site header"
default_theme:
  default: "light"
  type: string
  description: "Force light theme as default"
